-- migrate:up

INSERT INTO specialisms (id, name) VALUES
  (1, 'DERECHOS HUMANOS'),
  (2, 'DERECHO INTERNACIONAL'),
  (3, 'DERECHO CORPORATIVO O EMPRESARIAL'),
  (4, 'DERECHO CIVIL'),
  (5, 'DERECHO PENAL'),
  (6, 'DERECHO MERCANTIL'),
  (7, 'DERECHO TRIBUTARIO'),
  (8, 'DERECHO LABORAL'),
  (9,'CRIMINOLOGIA'),
  (10,'DERECHO ADMINISTRATIVO');

-- migrate:down

TRUNCATE specialisms;